server:
  port: 9004

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@localhost:9001/eureka/

spring:
  application:
    name: server-web
  cloud:
    loadbalancer:
      retry:
        enabled: false