spring:
  main:
    allow-circular-references: true
  application:
    name: server-client
  cloud:
    loadbalancer:
      retry:
        enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wangchan
    password: ps123456#
    url: jdbc:mysql://101.43.212.208:3306/spc?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 101.43.212.208
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ps1993#
      # 连接超时时间（毫秒）
    timeout: 1000
      # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.client.model
tencen:
  secretId: 
  secretKey: 
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

